<?php

return [

    'af' => ['afghanistan', 'af'],
    'ax' => ['åland islands', 'aland islands', 'ax'],
    'al' => ['albania', 'al'],
    'dz' => ['algeria', 'dz'],
    'as' => ['american samoa', 'as'],
    'ad' => ['andorra', 'ad'],
    'ao' => ['angola', 'ao'],
    'ai' => ['anguilla', 'ai'],
    'aq' => ['antarctica', 'aq'],
    'ag' => ['antigua and barbuda', 'antigua barbuda', 'ag'],
    'ar' => ['argentina', 'ar'],
    'am' => ['armenia', 'am'],
    'aw' => ['aruba', 'aw'],
    'au' => ['australia', 'au'],
    'at' => ['austria', 'at'],
    'az' => ['azerbaijan', 'az'],

    'bs' => ['bahamas', 'the bahamas', 'bs'],
    'bh' => ['bahrain', 'bh'],
    'bd' => ['bangladesh', 'bd'],
    'bb' => ['barbados', 'bb'],
    'by' => ['belarus', 'by'],
    'be' => ['belgium', 'be'],
    'bz' => ['belize', 'bz'],
    'bj' => ['benin', 'bj'],
    'bm' => ['bermuda', 'bm'],
    'bt' => ['bhutan', 'bt'],
    'bo' => ['bolivia', 'bo', 'bolivia plurinational state of'],
    'ba' => ['bosnia and herzegovina', 'bosnia herzegovina', 'ba'],
    'bw' => ['botswana', 'bw'],
    'bv' => ['bouvet island', 'bv'],
    'br' => ['brazil', 'br'],
    'io' => ['british indian ocean territory', 'io'],
    'bn' => ['brunei darussalam', 'brunei', 'bn'],
    'bg' => ['bulgaria', 'bg'],
    'bf' => ['burkina faso', 'bf'],
    'bi' => ['burundi', 'bi'],

    'kh' => ['cambodia', 'kh'],
    'cm' => ['cameroon', 'cm'],
    'ca' => ['canada', 'ca'],
    'cv' => ['cape verde', 'cabo verde', 'cv'],
    'ky' => ['cayman islands', 'ky'],
    'cf' => ['central african republic', 'cf'],
    'td' => ['chad', 'td'],
    'cl' => ['chile', 'cl'],
    'cn' => ['china', 'cn'],
    'cx' => ['christmas island', 'cx'],
    'cc' => ['cocos islands', 'keeling islands', 'cocos keeling islands', 'cc'],
    'co' => ['colombia', 'co'],
    'km' => ['comoros', 'km'],
    'cg' => ['congo', 'republic of the congo', 'cg'],
    'cd' => ['congo democratic republic of the', 'democratic republic of congo', 'dr congo', 'cd'],
    'ck' => ['cook islands', 'ck'],
    'cr' => ['costa rica', 'cr'],
    'ci' => ["cote d'ivoire", "côte d'ivoire", 'ivory coast', 'ci'],
    'hr' => ['croatia', 'hr'],
    'cu' => ['cuba', 'cu'],
    'cy' => ['cyprus', 'cy'],
    'cz' => ['czech republic', 'czechia', 'cz'],

    'dk' => ['denmark', 'dk'],
    'dj' => ['djibouti', 'dj'],
    'dm' => ['dominica', 'dm'],
    'do' => ['dominican republic', 'do'],

    'ec' => ['ecuador', 'ec'],
    'eg' => ['egypt', 'eg'],
    'sv' => ['el salvador', 'sv'],
    'gq' => ['equatorial guinea', 'gq'],
    'er' => ['eritrea', 'er'],
    'ee' => ['estonia', 'ee'],
    'et' => ['ethiopia', 'et'],

    'fj' => ['fiji', 'fj'],
    'fi' => ['finland', 'fi'],
    'fr' => ['france', 'fr'],
    'gf' => ['french guiana', 'gf'],
    'pf' => ['french polynesia', 'pf'],
    'tf' => ['french southern territories', 'tf'],

    'ga' => ['gabon', 'ga'],
    'gm' => ['gambia', 'gm'],
    'ge' => ['georgia', 'ge'],
    'de' => ['germany', 'de'],
    'gh' => ['ghana', 'gh'],
    'gi' => ['gibraltar', 'gi'],
    'gr' => ['greece', 'gr'],
    'gl' => ['greenland', 'gl'],
    'gd' => ['grenada', 'gd'],
    'gp' => ['guadeloupe', 'gp'],
    'gu' => ['guam', 'gu'],
    'gt' => ['guatemala', 'gt'],
    'gg' => ['guernsey', 'gg'],
    'gn' => ['guinea', 'gn'],
    'gw' => ['guinea-bissau', 'guinea bissau', 'gw'],
    'gy' => ['guyana', 'gy'],

    'ht' => ['haiti', 'ht'],
    'hm' => ['heard island and mcdonald islands', 'hm'],
    'va' => ['holy see', 'vatican city', 'vatican city state', 'va'],
    'hn' => ['honduras', 'hn'],
    'hk' => ['hong kong', 'hk'],
    'hu' => ['hungary', 'hu'],

    'is' => ['iceland', 'is'],
    'in' => ['india', 'in'],
    'id' => ['indonesia', 'id'],
    'ir' => ['iran', 'islamic republic of iran', 'ir'],
    'iq' => ['iraq', 'iq'],
    'ie' => ['ireland', 'ie'],
    'im' => ['isle of man', 'im'],
    'il' => ['israel', 'il'],
    'it' => ['italy', 'it'],

    'jm' => ['jamaica', 'jm'],
    'jp' => ['japan', 'jp'],
    'je' => ['jersey', 'je'],
    'jo' => ['jordan', 'jo'],

    'kz' => ['kazakhstan', 'kz'],
    'ke' => ['kenya', 'ke'],
    'ki' => ['kiribati', 'ki'],

    'kp' => ["korea democratic people's republic of", 'north korea', 'kp'],
    'kr' => ['korea republic of', 'south korea', 'kr'],

    'kw' => ['kuwait', 'kw'],
    'kg' => ['kyrgyzstan', 'kg'],

    'la' => ["lao people's democratic republic", 'laos', 'la'],
    'lv' => ['latvia', 'lv'],
    'lb' => ['lebanon', 'lb'],
    'ls' => ['lesotho', 'ls'],
    'lr' => ['liberia', 'lr'],
    'ly' => ['libya', 'ly'],
    'li' => ['liechtenstein', 'li'],
    'lt' => ['lithuania', 'lt'],
    'lu' => ['luxembourg', 'lu'],

    'mo' => ['macao', 'macau', 'mo'],
    'mk' => ['macedonia', 'north macedonia', 'mk'],
    'mg' => ['madagascar', 'mg'],
    'mw' => ['malawi', 'mw'],
    'my' => ['malaysia', 'my'],
    'mv' => ['maldives', 'mv'],
    'ml' => ['mali', 'ml'],
    'mt' => ['malta', 'mt'],
    'mh' => ['marshall islands', 'mh'],
    'mq' => ['martinique', 'mq'],
    'mr' => ['mauritania', 'mr'],
    'mu' => ['mauritius', 'mu'],
    'yt' => ['mayotte', 'yt'],
    'mx' => ['mexico', 'mx'],
    'fm' => ['micronesia', 'fm'],
    'md' => ['moldova', 'republic of moldova', 'md'],
    'mc' => ['monaco', 'mc'],
    'mn' => ['mongolia', 'mn'],
    'me' => ['montenegro', 'me'],
    'ms' => ['montserrat', 'ms'],
    'ma' => ['morocco', 'ma'],
    'mz' => ['mozambique', 'mz'],
    'mm' => ['myanmar', 'burma', 'mm'],

    'na' => ['namibia', 'na'],
    'nr' => ['nauru', 'nr'],
    'np' => ['nepal', 'np'],
    'nl' => ['netherlands', 'holland', 'nl'],
    'nc' => ['new caledonia', 'nc'],
    'nz' => ['new zealand', 'nz'],
    'ni' => ['nicaragua', 'ni'],
    'ne' => ['niger', 'ne'],
    'ng' => ['nigeria', 'ng'],
    'nu' => ['niue', 'nu'],
    'nf' => ['norfolk island', 'nf'],
    'mp' => ['northern mariana islands', 'mp'],
    'no' => ['norway', 'no'],

    'om' => ['oman', 'om'],

    'pk' => ['pakistan', 'pk'],
    'pw' => ['palau', 'pw'],
    'ps' => ['palestine', 'palestinian territory occupied', 'ps'],
    'pa' => ['panama', 'pa'],
    'pg' => ['papua new guinea', 'pg'],
    'py' => ['paraguay', 'py'],
    'pe' => ['peru', 'pe'],
    'ph' => ['philippines', 'ph'],
    'pn' => ['pitcairn', 'pn'],
    'pl' => ['poland', 'pl'],
    'pt' => ['portugal', 'pt'],
    'pr' => ['puerto rico', 'pr'],
    'qa' => ['qatar', 'qa'],

    're' => ['reunion', 'réunion', 're'],
    'ro' => ['romania', 'ro'],
    'ru' => ['russia', 'russian federation', 'ru'],
    'rw' => ['rwanda', 'rw'],

    'sh' => ['saint helena', 'sh'],
    'kn' => ['saint kitts and nevis', 'kn'],
    'lc' => ['saint lucia', 'lc'],
    'pm' => ['saint pierre and miquelon', 'pm'],
    'vc' => ['saint vincent and the grenadines', 'vc'],

    'ws' => ['samoa', 'ws'],
    'sm' => ['san marino', 'sm'],
    'st' => ['sao tome and principe', 'st'],
    'sa' => ['saudi arabia', 'sa'],
    'sn' => ['senegal', 'sn'],
    'rs' => ['serbia', 'rs'],
    'sc' => ['seychelles', 'sc'],
    'sl' => ['sierra leone', 'sl'],
    'sg' => ['singapore', 'sg'],
    'sk' => ['slovakia', 'sk'],
    'si' => ['slovenia', 'si'],
    'sb' => ['solomon islands', 'sb'],
    'so' => ['somalia', 'so'],
    'za' => ['south africa', 'za'],
    'es' => ['spain', 'es'],
    'lk' => ['sri lanka', 'lk'],
    'sd' => ['sudan', 'sd'],
    'sr' => ['suriname', 'sr'],
    'sj' => ['svalbard and jan mayen', 'sj'],
    'sz' => ['eswatini', 'swaziland', 'sz'],
    'se' => ['sweden', 'se'],
    'ch' => ['switzerland', 'ch'],
    'sy' => ['syria', 'sy', 'syrian arab republic', 'سوريا'],

    'tw' => ['taiwan', 'tw'],
    'tj' => ['tajikistan', 'tj'],
    'tz' => ['tanzania', 'united republic of tanzania', 'tz'],
    'th' => ['thailand', 'th'],
    'tl' => ['timor-leste', 'east timor', 'tl'],
    'tg' => ['togo', 'tg'],
    'tk' => ['tokelau', 'tk'],
    'to' => ['tonga', 'to'],
    'tt' => ['trinidad and tobago', 'tt'],
    'tn' => ['tunisia', 'tn'],
    'tr' => ['turkey', 'turkiye', 'tr'],
    'tm' => ['turkmenistan', 'tm'],
    'tc' => ['turks and caicos islands', 'tc'],
    'tv' => ['tuvalu', 'tv'],

    'ug' => ['uganda', 'ug'],
    'ua' => ['ukraine', 'ua'],
    'ae' => ['united arab emirates', 'uae', 'ae'],
    'gb' => ['united kingdom', 'uk', 'gb'],
    'us' => ['united states', 'usa', 'us', 'united states of america'],
    'um' => ['united states minor outlying islands', 'um'],
    'uy' => ['uruguay', 'uy'],
    'uz' => ['uzbekistan', 'uz'],

    'vu' => ['vanuatu', 'vu'],
    've' => ['venezuela', 've'],
    'vn' => ['vietnam', 'vn'],
    'vg' => ['virgin islands british', 'vg'],
    'vi' => ['virgin islands us', 'vi'],

    'wf' => ['wallis and futuna', 'wf'],
    'eh' => ['western sahara', 'eh'],
    'ye' => ['yemen', 'ye'],
    'zm' => ['zambia', 'zm'],
    'zw' => ['zimbabwe', 'zw'],
];